version: 2
jobs:
  build:
    environment:
      DOCKER_IMAGE_NAME: human-and-plant-disease-detection-with-health-and-fitness-recommendation
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD 
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=${DOCKER_IMAGE_NAME}' >> $BASH_ENV
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - setup_remote_docker
      - run:
          name: Build and push Docker image
          command: |
            docker build -t $DOCKERHUB_USER/$IMAGE_NAME:$TAG .
            echo "$DOCKERHUB_PASSWORD" | docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD docker.io
            
            docker push $DOCKERHUB_USER/$IMAGE_NAME:$TAG
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: main
